FROM ruby:3.1-slim

WORKDIR /workspace

COPY . .

# log 避けで tmp/ 以下がないので作成して bundler の設定を追加

RUN mkdir -p tmp/pids && \
		bundle config set --local path /workspace/vendor

CMD RACK_ENV=production bundle exec puma -C config/puma.rb
