#!/usr/bin/env bash

set -e

if which foreman >/dev/null; then
  foreman start -f Procfile.dev
else
  echo "Install overmind or modify exe/dev to use a different Procfile launcher."
  echo "https://github.com/theforeman/foreman"
fi
